#%RAML 1.0
title: Major Assessment Varun API
mediaType:
  - application/json
protocols:
  - HTTP
types:
  GetMilestone1DataType:
    items:
      properties:
        id:
          example: 2482
          type: number
          format: int
        name:
          example: Kartik Kocchar
          type: string
        email:
          example: kartik_kocchar@rutherford.io
          type: string
        gender:
          example: female
          type: string
        status:
          example: inactive
          type: string
  PostMilestone2DataType:
    properties:
      post_id:
        example: 2003
        type: number
        format: int
  PostResponseMilestone2DataType:
    properties:
      Userdetails:
        items:
          properties:
            post_id:
              example: 2003
              type: number
              format: int
            id:
              example: 1978
              type: number
              format: int
            name:
              example: Bhaaswar Pothuvaal III
              type: string
  GetMilestone3DataType:
    properties:
      Name:
        example: Gorakhanatha Chaturvedi
        type: string
      Status:
        example: active
        type: string
      Gender:
        example: female
        type: string
description: Major Assessment API - Varun
/milestone1:
  get:
    responses:
      "200":
        body:
          type: GetMilestone1DataType
/milestone2:
  post:
    body:
      type: PostMilestone2DataType
    responses:
      "201":
        body:
          type: PostResponseMilestone2DataType
/milestone3:
  get:
    responses:
      "200":
        body:
          type: GetMilestone3DataType
